### ISSUE TITLE
Allow indexing multiple sections into one collection

### ISSUE THREAD

**Issue by sidoneill** [percipioglobal/craft-typesense#35]
Commonly on most sites we use this plugin on we index multiple sections / entry types into one collection. It's easy to change the criteria for a full sync to accomplish this:

```
->criteria(function(\craft\elements\db\EntryQuery $query) {
			return $query->section(['pages','places']);
		}),
```
However this obviously doesn't take into account indexing individual entries when they are saved. To accomplish this we've started adapting the plugin code in the Collection helper _getCollectionBySection_ function to check if the currently saved entry exists in an array, if the collection index section is an array:

```
foreach ($indexes as $index) {
            if ($index->section === $name OR (is_array($index->section) AND in_array($name,$index->section))) {
                return $index;
            }
        }
```

This then allows us to use an array in the typesense.php file to index multiple sections into the same collection.
```
'section' => ['places.default','pages.default'],
```

I was wondering if there was already a way to accomplish this that I've missed, or if something along these lines could be added?

Thanks!

**Comment by michtio** [comment]
@sidoneill loving this feature request!

We are currently working on a major improvement/refactor of the entire Typesense plugin, we have added it to the backlog. Thank you for this!

**Comment by sidoneill** [comment]
@michtio You guys are awesome! I didn’t bother with a pull request as I had an inkling you had some things in progress. This is a great plugin and such a useful time-saver. Thank you!

**Comment by michtio** [comment]
@sidoneill I am happy you find it useful, as an update, the multi section feature will be released somewhere this week, it has been picked up in our sprint ;)

**Comment by michtio** [comment]
Typesense for Craft 4 and 5 has been released with this functionality

**Comment by michtio** [comment]
Typesense for Craft 4 and 5 has been released with this functionality
