### ISSUE TITLE
How to install & use typesense for craft cms5

### ISSUE THREAD

**Issue by boldpaul** [percipioglobal/craft-typesense#37]
Hi,

currently trying to incorporate typesense into my project which has many properties & assets, i want users to search through all of these. 

However, the documentation for installing & using typesense within twig and/or javascript for craft 5 seems incomplete. 

Is this something that will be updated with examples on how to set up typesense? Or should i explore other options.

Let me know. Thanks.

**Comment by cookie10codes** [comment]
hi @boldpaul, sorry for my late reply. We have plans on doing a big update which also includes documentation on how to use. We don't have any updates tho on when this will happen.

**Some help on setting up your environment:**
Currently the setup for Craft 5 is the same as Craft 4. The most convenient way to use, is setup an account on Typesense Cloud. When you setup the account, you'll need to generate the API keys, these will be needed to connect Typesense to your Craft install.

After you setup the Typesense Cloud, you can move over to the Typesense plugin settings, make sure to select Cluster as Typesense Server Type. Depending on the amount of clusters setup, add them in a ; seperated manner to connect (preferable through .env file). The Nearest node is the one closest to where your server will live, this will have some effect on the speed of the search. The port for Typesense Cloud is 443, Protocal will be http. The api key is the one needed to sync your entries with Typesense, the Search only will only be used to read from.

**Implementing Typesense search in your frontend:**
To integrate Typesense inside of your frontend, we don't have any exact examples to show, we're also working on those. Depending on how you will implement this on your site. The most common one to use is the instantsearch https://github.com/typesense/typesense-instantsearch-adapter. Which is connected to javascript, you can choose between vanille javascript, react, vue or angular. On the Typesense site, you'll find an example with a demo https://typesense.org/docs/guide/search-ui-components.html. 

I hope this will help you setup and getting started. Re-open the issue if you have any further questions
