### ISSUE TITLE
[Feature Request] Allow indexing multiple element types

### ISSUE THREAD

**Issue by sidoneill** [percipioglobal/craft-typesense#43]
Sometimes on sites we index entries AND other element types to the same index – most commonly when we use the Craft Shopify plugin. I noticed that Craft Commerce element types are possible in [this pull request](https://github.com/craftpulse/craft-typesense/pull/36). I'm accomplishing this right now for a soon-to-launch site by adding this to the CollectionsController.php

 ```
case 'craft\shopify\elements\Product':
    $variables['sections'][] = [
        'id' => 'shopify-products',
        'name' => 'Products',
        'handle' => 'products',
        'type' => 'Product: product',
        'entryCount' => $index->criteria->count(),
        'index' => $index->indexName,
      ];
  break;
```

And then also doing a nasty little hack to the SyncDocumentsJob.php to overwrite the collection that is indexed to in the upsert call.

Obviously this isn't the right way to accomplish this long term. The Craft Scout plugin added a function to allow you to override the criteria and elementType with `->getElements(callable $queries)`. ([Docs](https://studioespresso.github.io/craft-scout/multiple-element-types.html) and [the relevant code](https://github.com/studioespresso/craft-scout/blob/6524c812a736754a1d0370573d122b3e2cc574fc/src/ScoutIndex.php#L69)) Any chance of something similar to this at some point?

Thank you!

**Comment by cookie10codes** [comment]
Hi sidoneill, thanks for your reply. The commerce implementation is due to go out in the week starting from the 6th of January.<br><br>According to your multiple section, thinking out loud. Would it be an option to extend the query inside of the resolver to access multiple sections by parsing the sections as an array (Craft CMS docs: [https://craftcms.com/docs/5.x/reference/element-types/entries.html#section](https://craftcms.com/docs/5.x/reference/element-types/entries.html#section))

**Comment by sidoneill** [comment]
Thanks! The commerce implementation I saw would unfortunately not cover this case as the Shopify plugin is not part of Craft Commerce (unless I missed something in that!).

It's not possible to include this element type in the resolver as the products the Shopify plugin uses are not an Entry type, like Commerce they are a different type of element (not `craft\elements\Entry` but `craft\shopify\elements\Product`).

Hope that makes sense!

**Comment by cookie10codes** [comment]
@sidoneill I tested and included Shopify products as supported type. It's in development te test, we will also release this in the week of the 6th of January. 

Thanks for your input

https://github.com/craftpulse/craft-typesense/pull/44
